server:
  port: 8080

spring:
  application:
    name: gpt-gateway-service

  main:
    allow-bean-definition-overriding: true

  # ai:
    # openai:
      # api-key: 



mms:
  service:
    url: http://mms-service/api
