server:
  port: 8080

spring:
  application:
    name: gpt-gateway-service

  main:
    allow-bean-definition-overriding: true

  ai:
    openai:
      api-key: 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



mms:
  service:
    url: http://mms-service/api
